# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"U\n\x1c\x43\x61lculateUserTotalSumRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x12\n\nstart_from\x18\x02 \x01(\r\x12\x10\n\x08\x65nd_from\x18\x03 \x01(\r\"F\n\x1d\x43\x61lculateUserTotalSumResponse\x12\r\n\x05value\x18\x01 \x01(\r\x12\x16\n\x0e\x65xecution_time\x18\x02 \x01(\r2r\n\x0bTransaction\x12\x63\n\nsum_amount\x12).transaction.CalculateUserTotalSumRequest\x1a*.transaction.CalculateUserTotalSumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CALCULATEUSERTOTALSUMREQUEST']._serialized_start=34
  _globals['_CALCULATEUSERTOTALSUMREQUEST']._serialized_end=119
  _globals['_CALCULATEUSERTOTALSUMRESPONSE']._serialized_start=121
  _globals['_CALCULATEUSERTOTALSUMRESPONSE']._serialized_end=191
  _globals['_TRANSACTION']._serialized_start=193
  _globals['_TRANSACTION']._serialized_end=307
# @@protoc_insertion_point(module_scope)
