version: "3.10"

services:
  database:
    container_name: database
    image: postgres:16
    ports:
      - ${DB_PORT:-6432}:${DB_PORT:-6432}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_DATABASE:-postgres}
      - POSTGRES_USER=${DB_USER:-test}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-test}
      - POSTGRES_HOST=${DB_HOST:-test}
      - PGPORT=${DB_PORT:-6432}

  application:
    container_name: application
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_DATABASE=${DB_DATABASE:-postgres}
      - DB_USER=${DB_USER:-test}
      - DB_PASSWORD=${DB_PASSWORD:-test}
      - DB_HOST=database
      - DB_PORT=${DB_PORT:-6432}
      - APPLICATION_HOST=${APPLICATION_HOST:-0.0.0.0}
      - APPLICATION_PORT=${APPLICATION_PORT:-50501}
    ports:
      - ${APPLICATION_PORT:-50501}:${APPLICATION_PORT:-50501}